### ISSUE TITLE
[Streams] Duplicate class org.reactivestreams.XYZ found in modules

### ISSUE THREAD

**Issue by dpmaddy** [mirego/trikot#160]
Build error, `Duplicate class org.reactivestreams.XYZ` found in modules ...

```
Duplicate class org.reactivestreams.Processor found in modules reactive-streams-1.0 (org.reactivestreams:reactive-streams:1.0.0) and streams-debug-runtime (com.mirego.trikot:streams-android-debug:4.3.0)
Duplicate class org.reactivestreams.Publisher found in modules reactive-streams-1.0 (org.reactivestreams:reactive-streams:1.0.0) and streams-debug-runtime (com.mirego.trikot:streams-android-debug:4.3.0)
Duplicate class org.reactivestreams.Subscriber found in modules reactive-streams-1.0 (org.reactivestreams:reactive-streams:1.0.0) and streams-debug-runtime (com.mirego.trikot:streams-android-debug:4.3.0)
Duplicate class org.reactivestreams.Subscription found in modules reactive-streams-1.0 (org.reactivestreams:reactive-streams:1.0.0) and streams-debug-runtime (com.mirego.trikot:streams-android-debug:4.3.0)
```

```gradle
// shared/build.gradle.kts

val trikotVersion = "4.3.0"

// ...

kotlin {
    listOf(
        iosX64(), iosArm64(), iosSimulatorArm64()
    ).forEach {
        it.binaries.framework {
            baseName = "shared"
            export("com.mirego.trikot:bluetooth:$trikotVersion")
            export("com.mirego.trikot:streams:$trikotVersion")
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                // ...
                implementation("com.mirego.trikot:streams:$trikotVersion")
                implementation("com.mirego.trikot:bluetooth:$trikotVersion")
            }
        }

        // ...
    }
}

// ...
```

I've been battling trying to figure how to remedy this error, but have had no luck. Is there any chance this kind of problem has been seen before or would anyone have any suggestions as to how I might fix?

If any more info on my project configuration would help please let me know. I'm more uncertain if this is a problem with the packages I've chosen or whether its something I'm doing wrong :)

_EDIT:_
I seemed to fix this issue after doing some digging in the source of your `stream` package, by updating the following line,

```gradle
implementation("com.mirego.trikot:bluetooth:$trikotVersion") {
    exclude(group = "org.reactivestreams")
}
```

Would anyone foresee this to cause any major problems? I'm a bit of a gradle newbie so am unsure what exactly this does.

**Comment by npresseault** [comment]
You should actually do the opposite as the `org.reactivestreams` artefact isn't available as a kmm module. In fact this is the very reason for the existence of the `org.reactivestreams` package in `trikot.streams`.

What you should do instead of going per individual dependency (because it could setupped as a transitive dependency) is setup a dependency substitution strategy.

Assuming you have org.reactivestreams

**build.gradle.kts**
```
configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            substitute(module("org.reactivestreams:reactive-streams:$reactive_streams_version")).using(module("com.mirego.trikot:streams:$trikot_version"))
        }
        cacheDynamicVersionsFor(60, "seconds")
    }
}
```

**build.gradle**
```
configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            substitute module("org.reactivestreams:reactive-streams:$reactive_streams_version") with module("com.mirego.trikot:streams:$trikot_version")
        }
        cacheDynamicVersionsFor 60, 'seconds'
    }
}
```

**Comment by dpmaddy** [comment]
Thanks heaps for the reply! Ah ok, that makes sense. 

So to clarify, in the first option (`configurations.all`) when compiling we replace all instances of the package `org.reactivestreams:reactive-streams` with the `trikot.streams` `org.reactivestreams` package so that it is available in iOS, Android, and other platforms (so multiplatform)?

In the second option, you've excluded the package from all builds, which to me looks like an extension of what I was doing originally in my "fix" but for every config (rather than just for `commonMain`)?

With the first option, I'm picking the `org.reactivestreams` package will compile to multiplatform code (i.e. can be used in iOS) but in the second, we remove and therefore won't have access anywhere but our `shared:` code?

I've given both of these a try but only the second option seemed to work. The first with `resolutionStratergy` doesn't seem to build, with the same error as originally shown.

Again, thanks for any and all direction on debugging/fixing this, it is greatly appreciated :)

**Comment by npresseault** [comment]
> So to clarify, in the first option (configurations.all) when compiling we replace all instances of the package org.reactivestreams:reactive-streams with the trikot.streams org.reactivestreams package so that it is available in iOS, Android, and other platforms (so multiplatform)?

Indeed

> In the second option, you've excluded the package from all builds, which to me looks like an extension of what I was doing originally in my "fix" but for every config (rather than just for commonMain)?

Oh yeah you are totally right about it being the same if that dependency is pulled only from trikot.bluetooth. Just took a deeper look and it seems the` org.reactivestreams` is pulled transitively by `androidx.lifecycle:lifecycle-reactivestreams-ktx` which is a dependency of `trikot.bluetooth`
See: https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-reactivestreams/2.6.0-rc01

Keep in mind the exclude works on dependency groups, not packages thought.

> With the first option, I'm picking the org.reactivestreams package will compile to multiplatform code (i.e. can be used in iOS) but in the second, we remove and therefore won't have access anywhere but our shared: code?

Second option, you should be able to use the `org.reactivestreams` package which is embeded from `trikot.streams` as long as you either import the `trikot.streams` in your common module or import `trikot.bluetooth` dependency transitively with the [api declaration instead of implementation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation)
